from __future__ import annotations

import json
from pathlib import Path
from pprint import pformat

try:
    from .kkk_declarative import KANATA_KEYHAC_KOMOREBI_SPEC
except ImportError:
    from kkk_declarative import KANATA_KEYHAC_KOMOREBI_SPEC


REPO_ROOT = Path(__file__).resolve().parents[2]
KANATA_REPO_ROOT = REPO_ROOT.parent.parent / "kanata_config"
KEYHAC_DOC_PATH = REPO_ROOT / "docs" / "architecture" / "KKK.md"
KANATA_DOC_PATH = KANATA_REPO_ROOT / "KKK.md"
KEYHAC_GENERATED_PATH = REPO_ROOT / "generated" / "kkk" / "generated_kkk_bindings.py"
KANATA_GENERATED_PATH = KANATA_REPO_ROOT / "generated_kkk_bindings.kbd"
JSON_EXPORT_PATH = REPO_ROOT / "generated" / "kkk" / "generated_kkk_bindings.json"


def render_keyhac_generated() -> str:
    payload = pformat(KANATA_KEYHAC_KOMOREBI_SPEC, width=100, sort_dicts=False)
    return (
        "# Auto-generated by tools/generators/generate_kkk_bindings.py\n"
        "# This file is intentionally descriptive first. Live wiring can import\n"
        "# generated subsets later without forcing the runtime onto generated config.\n\n"
        f"GENERATED_KKK_SPEC = {payload}\n"
    )


def render_kanata_generated() -> str:
    lines = [
        ";; Auto-generated by tools/generators/generate_kkk_bindings.py",
        ";; This file is not yet included by win_to_f19.kbd.",
        ";; It exists as the future generated contract for Kanata-owned combo routing.",
        "",
    ]

    for combo in KANATA_KEYHAC_KOMOREBI_SPEC["combo_intercepts"]:
        lines.append(f";; combo: {combo['id']}")
        lines.append(
            ";; mods="
            + "+".join(combo["mods"])
            + " physical="
            + "+".join(combo["physical_mods"])
            + f" key={combo['key']}"
        )
        lines.append(
            ";; action="
            + combo["action"]["type"]
            + " "
            + combo["action"]["path"]
            + " "
            + " ".join(combo["action"]["args"])
        )
        lines.append("")

    return "\n".join(lines) + "\n"


def render_doc(project: str) -> str:
    spec = KANATA_KEYHAC_KOMOREBI_SPEC
    lines = [
        "# KKK",
        "",
        "KKK = Kanata + Keyhac + Komorebi.",
        "",
        "## Layering",
        "",
        "- Kanata owns physical-key interception, layer routing, and multi-mod printable combos.",
        "- Keyhac owns Python workflows, shared state, list UI, launchers, and app-specific logic.",
        "- Komorebi owns the actual window-manager side effects and bar visibility state.",
        "",
        "## Declarative Source",
        "",
        "- Source of truth: `tools/generators/kkk_declarative.py` in the keyhac repo.",
        "- Generator: `tools/generators/generate_kkk_bindings.py` in the keyhac repo.",
        "- Generated exports:",
        "  - `generated/kkk/generated_kkk_bindings.py`",
        "  - `generated_kkk_bindings.kbd` in the kanata_config repo",
        "",
        "## Current Patterns",
        "",
    ]

    for export in spec["modifier_exports"]:
        lines.append(
            f"- modifier-export `{export['id']}`: `{export['physical_key']}` -> "
            f"`{export['kanata_output']}` -> `{export['keyhac_user_modifier']}`"
        )

    for sync in spec["state_sync"]:
        lines.append(
            f"- state-sync `{sync['id']}`: `{sync['source']}` owns modal state and updates "
            f"shared state through `{sync['helper']['path'].split('automation\\\\', 1)[-1]}`."
        )

    for command in spec["kanata_direct_commands"]:
        if command["id"] == "km_toggle_modal":
            lines.append(
                "- direct-command `km_toggle_modal`: `Ctrl+Caps` / `Caps+Ctrl` toggles Kanata's "
                "`base/modal` layer and writes shared modal state."
            )
            continue

        if command["id"].startswith("km_core_"):
            lines.append(
                f"- direct-command `{command['id']}`: `{command['action']['note']}`"
            )
            continue

        lines.append(
            f"- direct-command `{command['id']}`: modal `{command['key']}` runs "
            f"`{' '.join(command['action']['args'])}`."
        )

    for combo in spec["combo_intercepts"]:
        lines.append(
            f"- combo-intercept `{combo['id']}`: "
            f"`{'+'.join(combo['mods'])}+{combo['key']}` is Kanata-owned and runs "
            f"`{combo['action']['type']}` directly."
        )

    lines.extend(
        [
            "",
            "## Ownership Summary",
            "",
            f"- Default KKK runtime backend: `{spec['runtime_defaults']['komorebi_hotkey_backend']}`.",
            f"- {spec['runtime_defaults']['ownership_note']}",
            "- Bare `U1+U2` / `U2+U1` intentionally has no action.",
        ]
    )

    lines.extend(
        [
            "",
            "## Expansion Rule",
            "",
            "- For `u3/u4/u5 + printable key`, prefer Kanata combo interception.",
            "- If the action is short and stateless, let Kanata run it directly.",
            "- If the action needs Python/UI/state, let Kanata emit a stable signal and let Keyhac handle it.",
            "",
            "## Project Note",
            "",
            f"- This copy lives in the `{project}` repo as a local reading guide.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    KEYHAC_GENERATED_PATH.write_text(render_keyhac_generated(), encoding="utf-8")
    KANATA_GENERATED_PATH.write_text(render_kanata_generated(), encoding="utf-8")
    JSON_EXPORT_PATH.write_text(
        json.dumps(KANATA_KEYHAC_KOMOREBI_SPEC, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    KEYHAC_DOC_PATH.write_text(render_doc("keyhac"), encoding="utf-8")
    KANATA_DOC_PATH.write_text(render_doc("kanata_config"), encoding="utf-8")


if __name__ == "__main__":
    main()
